apiVersion: v1
kind: ConfigMap
metadata:
  name: cpro-config-map
  namespace: cpro-kube-app-ns
  labels:
    app: cpro-application
    subname: configmap
type: Opaque
data:
  service.url.commission: FROM_KUBERNETES_SERVICE
  service.url.interest: FROM_KUBERNETES_SERVICE
  service.url.payment: FROM_KUBERNETES_SERVICE

