apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: ibm.io/ibmc-block
  labels:
    app: mysql
    region: us-south
    zone: sjc03
  name: mysql-claim
  namespace: cpro-kube-app-ns
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-block-bronze
